# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mood',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='price',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='taste',
            field=models.NullBooleanField(default=False),
        ),
    ]
