# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20151231_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mood',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='taste',
            field=models.BooleanField(default=False),
        ),
    ]
