# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_obejct1'),
        ('users', '0002_auto_20151231_1032'),
        ('comment', '0007_auto_20151231_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=500, null=True)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.USER')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commenta',
            unique_together=set([('coffee', 'user')]),
        ),
    ]
