# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_commenta_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coffeeid', models.CharField(max_length=5000)),
            ],
        ),
    ]
