# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
